import Head from 'next/head'
import styled from 'styled-components'
import { useWeb3 } from '@3rdweb/hooks'
import Dashboard from './Dashboard'

export default function Home() {

  const { address, connectWallet } = useWeb3()

  return (
    <div>
      <Head>
        <title>Coinbase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://play-lh.googleusercontent.com/PjoJoG27miSglVBXoXrxBSLveV6e3EeBPpNY55aiUUBM9Q1RCETKCOqdOkX2ZydqVf0" />
      </Head>

      <Wrapper>
        {address ? (
          <Dashboard address={address} />
        ) : (
          <WalletConnect>
            <Button onClick={() => connectWallet('injected')}>
              Connect Wallet
            </Button>
            <Details>
              Login And Connect Your Wallet.
            </Details>
          </WalletConnect>
        )}
      </Wrapper>
    </div>
  )
}

const Wrapper = styled.div`
  display: flex;
  height: 100vh;
  max-width: 100vw;
  background-color: #0a0b0d;
  color: white;
  display: grid;
  place-items: center;
  overflow-x: hidden;
`

const WalletConnect = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Button = styled.div`
  border: 1px solid #282b2f;
  padding: 0.8rem;
  font-size: 1.3rem;
  font-weight: 500;
  border-radius: 0.4rem;
  background-color: #3773f5;
  color: #000;
  &:hover {
    cursor: pointer;
  }
`

const Details = styled.div`
  font-size: 1.2rem;
  text-align: center;
  margin-top: 1rem;
  font-weight: 500;
  color: #282b2f;
`